package com.restpartijen.api.security.repository

import org.jetbrains.exposed.v1.core.Table
import com.restpartijen.api.shared.Role
import org.jetbrains.exposed.v1.datetime.datetime

object UsersTable: Table ("users") {
    // The ID is the primary key and is generated by the database on insert. It is NEVER set by the application.
    val id = long("id").autoIncrement()

    // E-mail. This is also a Unique Key in the database. There cannot be another user with the same e-mail address.
    val email = varchar("email", length = 255).uniqueIndex()

    val password_hash = varchar("passwordhash", length = 255)
    val display_name = varchar("displayname", length = 255)

    // Role stored by its name (for example "COLLECTOR"), read back as a Role.
    val role = enumerationByName<Role>("role", length = 20)
    val created_At = datetime("created_at")


    // Tells Exposed (and the generated SQL) which column is the primary key.
    override val primaryKey = PrimaryKey(id)
}