package com.restpartijen.api.product.repository

import org.jetbrains.exposed.v1.core.Table

/** * Table definition for surplus products (ERD §9.1, table SURPLUS_PRODUCTS). * * Walking skeleton version: only three columns to prove the chain * route -> service -> repository -> table works. The remaining columns * from the ERD are added in F1 T2. */
object ProductsTable : Table("surplus_products") {
    // Generated by the database on insert; never set by the application.
    val id = long("id").autoIncrement()

    // Product name as shown to collectors.
    val name = varchar("name", length = 255)

    // Stored as text for now. Becomes the ProductCategory enum once
// the shared types exist (block 4). Single table inheritance uses
// this column as the discriminator (§9.3).
    val category = varchar("category", length = 20)

    // Tells Exposed (and the generated SQL) which column is the primary key.
    override val primaryKey = PrimaryKey(id)
}
